from datetime import datetime, timezone
from enum import Enum

from sqlalchemy import DateTime, Enum as SQLEnum, ForeignKey, Index, String
from sqlalchemy.orm import Mapped, mapped_column

from app.core.database import Base


class AuditAction(str, Enum):
    LOGIN_SUCCESS = "LOGIN_SUCCESS"
    LOGIN_FAILURE = "LOGIN_FAILURE"
    LOGOUT = "LOGOUT"
    ACCOUNT_DEACTIVATED = "ACCOUNT_DEACTIVATED"
    ATTENDANCE_CHECKED_IN = "ATTENDANCE_CHECKED_IN"
    ATTENDANCE_CHECKED_OUT = "ATTENDANCE_CHECKED_OUT"
    LEAVE_APPLIED = "LEAVE_APPLIED"
    LEAVE_APPROVED = "LEAVE_APPROVED"
    LEAVE_REJECTED = "LEAVE_REJECTED"
    LEAVE_CANCELLED = "LEAVE_CANCELLED"
    LEAVE_REVOKED = "LEAVE_REVOKED"
    LEAVE_TYPE_CREATED = "LEAVE_TYPE_CREATED"
    LEAVE_TYPE_UPDATED = "LEAVE_TYPE_UPDATED"
    LEAVE_TYPE_ACTIVATED = "LEAVE_TYPE_ACTIVATED"
    LEAVE_TYPE_DEACTIVATED = "LEAVE_TYPE_DEACTIVATED"
    LEAVE_BALANCE_UPDATED = "LEAVE_BALANCE_UPDATED"
    PROJECT_CREATED = "PROJECT_CREATED"
    PROJECT_UPDATED = "PROJECT_UPDATED"
    PROJECT_STATUS_CHANGED = "PROJECT_STATUS_CHANGED"
    PROJECT_PROGRESS_UPDATED = "PROJECT_PROGRESS_UPDATED"
    PROJECT_ACTIVATED = "PROJECT_ACTIVATED"
    PROJECT_DEACTIVATED = "PROJECT_DEACTIVATED"
    EMPLOYEE_ASSIGNED_TO_PROJECT = "EMPLOYEE_ASSIGNED_TO_PROJECT"
    EMPLOYEE_REMOVED_FROM_PROJECT = "EMPLOYEE_REMOVED_FROM_PROJECT"
    PROJECT_ROLE_CREATED = "PROJECT_ROLE_CREATED"
    PROJECT_ROLE_UPDATED = "PROJECT_ROLE_UPDATED"
    PROJECT_ROLE_ACTIVATED = "PROJECT_ROLE_ACTIVATED"
    PROJECT_ROLE_DEACTIVATED = "PROJECT_ROLE_DEACTIVATED"
    ANNOUNCEMENT_CREATED = "ANNOUNCEMENT_CREATED"
    ANNOUNCEMENT_UPDATED = "ANNOUNCEMENT_UPDATED"
    ANNOUNCEMENT_PUBLISHED = "ANNOUNCEMENT_PUBLISHED"
    ANNOUNCEMENT_ARCHIVED = "ANNOUNCEMENT_ARCHIVED"
    ANNOUNCEMENT_READ = "ANNOUNCEMENT_READ"
    WORK_REPORT_CREATED = "WORK_REPORT_CREATED"
    COMPLAINT_CREATED = "COMPLAINT_CREATED"
    COMPLAINT_STATUS_UPDATED = "COMPLAINT_STATUS_UPDATED"
    COMPLAINT_PRIORITY_UPDATED = "COMPLAINT_PRIORITY_UPDATED"
    COMPLAINT_RESPONDED = "COMPLAINT_RESPONDED"
    COMPLAINT_RESOLVED = "COMPLAINT_RESOLVED"
    COMPLAINT_REJECTED = "COMPLAINT_REJECTED"
    COMPLAINT_CLOSED = "COMPLAINT_CLOSED"
    COMPLAINT_CATEGORY_CREATED = "COMPLAINT_CATEGORY_CREATED"
    COMPLAINT_CATEGORY_UPDATED = "COMPLAINT_CATEGORY_UPDATED"
    PERFORMANCE_REVIEW_CREATED = "PERFORMANCE_REVIEW_CREATED"
    PERFORMANCE_REVIEW_UPDATED = "PERFORMANCE_REVIEW_UPDATED"
    PERFORMANCE_REVIEW_COMPLETED = "PERFORMANCE_REVIEW_COMPLETED"
    PERFORMANCE_RATING_UPDATED = "PERFORMANCE_RATING_UPDATED"
    PERFORMANCE_GOAL_CREATED = "PERFORMANCE_GOAL_CREATED"
    PERFORMANCE_GOAL_UPDATED = "PERFORMANCE_GOAL_UPDATED"
    PERFORMANCE_GOAL_STATUS_CHANGED = "PERFORMANCE_GOAL_STATUS_CHANGED"



class AuditLog(Base):
    __tablename__ = "audit_logs"

    id: Mapped[int] = mapped_column(
        primary_key=True,
        autoincrement=True,
    )

    user_id: Mapped[int | None] = mapped_column(
        ForeignKey("users.id"),
        nullable=True,
        index=True,
    )

    action: Mapped[AuditAction] = mapped_column(
        SQLEnum(
            AuditAction,
            name="audit_action",
        ),
        nullable=False,
    )

    ip_address: Mapped[str | None] = mapped_column(
        String(45),
        nullable=True,
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
    )


Index(
    "ix_audit_logs_action",
    AuditLog.action,
)

Index(
    "ix_audit_logs_created_at",
    AuditLog.created_at,
)